Gem::Specification.new do |s|
s.name = 'aurora_file_processor'
s.version = '0.1.0'
s.date = '2014-03-12'
s.summary = "A gem to process energy and power files outputted by the Aurora Power-One inverter"
s.description = "The gem takes exactly one energy file and one power file generated by the inverter. The two filenames are enter on the command line without spaces (no order necessary)"
s.authors = ["Chris Ashfield"]
s.email = 'biodieselchris@gmail.com'
s.homepage = 'http://rubygems.org/gems/aurora_file_processor'
s.licenses = ['MIT']
s.files =  ["lib/aurora_file_processor.rb"]
s.executables = ["aurora_file_processor"]
end